"""Match HTTP endpoints: evaluate and retrieve one Profile x Opportunity verdict."""
from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.models import Opportunity, Profile
from app.schemas import MatchRead
from app.services.matches import evaluate_and_persist_match, get_match

router = APIRouter(tags=["matches"])

MATCH_PATH = "/profiles/{profile_id}/opportunities/{opportunity_id}/match"


def _not_found(db: Session, profile_id: uuid.UUID, opportunity_id: uuid.UUID) -> HTTPException:
    """Build the 404 explaining which parent (or the Match itself) is missing."""
    if db.get(Profile, profile_id) is None:
        detail = "Profile not found."
    elif db.get(Opportunity, opportunity_id) is None:
        detail = "Opportunity not found."
    else:
        detail = "Match not found."
    return HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=detail)


@router.post(MATCH_PATH, response_model=MatchRead, status_code=status.HTTP_200_OK)
def evaluate(
    profile_id: uuid.UUID,
    opportunity_id: uuid.UUID,
    db: Session = Depends(get_db),
) -> MatchRead:
    """Evaluate a profile against an opportunity and return the persisted Match.

    Idempotent for the Profile x Opportunity pair: re-evaluating updates the
    existing Match instead of creating another one. All verdicts, evidence
    and counts are server-generated by the matching service.
    """
    match = evaluate_and_persist_match(db, profile_id, opportunity_id)
    if match is None:
        raise _not_found(db, profile_id, opportunity_id)
    return match


@router.get(MATCH_PATH, response_model=MatchRead)
def get_one(
    profile_id: uuid.UUID,
    opportunity_id: uuid.UUID,
    db: Session = Depends(get_db),
) -> MatchRead:
    """Return the already persisted Match without triggering an evaluation."""
    match = get_match(db, profile_id, opportunity_id)
    if match is None:
        raise _not_found(db, profile_id, opportunity_id)
    return match
