"""add matches and match_requirements

Revision ID: 03d2e7c43211
Revises: b75b6507557d
Create Date: 2026-09-26 03:53:33.798032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d2e7c43211'
down_revision: Union[str, Sequence[str], None] = 'b75b6507557d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('eligible', 'potential_match', 'not_eligible', 'needs_review')", name='ck_matches_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'opportunity_id', name='uq_matches_profile_opportunity')
    )
    op.create_index('ix_matches_opportunity_id', 'matches', ['opportunity_id'], unique=False)
    op.create_table('match_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('actual', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('met', 'not_met', 'unknown', 'needs_review')", name='ck_match_requirements_outcome'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'requirement_id', name='uq_match_requirements_match_requirement')
    )
    op.create_index('ix_match_requirements_match_id', 'match_requirements', ['match_id'], unique=False)
    op.create_index('ix_match_requirements_requirement_id', 'match_requirements', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_requirements_requirement_id', table_name='match_requirements')
    op.drop_index('ix_match_requirements_match_id', table_name='match_requirements')
    op.drop_table('match_requirements')
    op.drop_index('ix_matches_opportunity_id', table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
