"""add profiles education and test scores

Revision ID: 166c17bb14f4
Revises: f32f798afa83
Create Date: 2026-09-24 23:47:18.614792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '166c17bb14f4'
down_revision: Union[str, Sequence[str], None] = 'f32f798afa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('citizenships', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('country_of_residence', sa.String(length=2), nullable=True),
    sa.Column('degree_level', sa.String(length=32), nullable=False),
    sa.Column('is_currently_enrolled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("degree_level IN ('high_school', 'associate', 'bachelor', 'master', 'doctorate', 'other')", name='ck_profiles_degree_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_profiles_country_of_residence', 'profiles', ['country_of_residence'], unique=False)
    op.create_index('ix_profiles_degree_level', 'profiles', ['degree_level'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('degree_level', sa.String(length=32), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('gpa_scale', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("degree_level IN ('high_school', 'associate', 'bachelor', 'master', 'doctorate', 'other')", name='ck_education_degree_level'),
    sa.CheckConstraint('(gpa IS NULL) = (gpa_scale IS NULL)', name='ck_education_gpa_scale_pair'),
    sa.CheckConstraint('gpa IS NULL OR gpa <= gpa_scale', name='ck_education_gpa_within_scale'),
    sa.CheckConstraint('gpa IS NULL OR gpa >= 0', name='ck_education_gpa_nonnegative'),
    sa.CheckConstraint('gpa_scale IS NULL OR gpa_scale IN (4, 5, 10, 100)', name='ck_education_gpa_scale_supported'),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name='ck_education_date_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_education_profile_id', 'education', ['profile_id'], unique=False)
    op.create_index('uq_education_primary_per_profile', 'education', ['profile_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('test_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('report_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_score >= 0', name='ck_test_scores_overall_score_nonnegative'),
    sa.CheckConstraint('test_date IS NULL OR expires_at IS NULL OR expires_at >= test_date', name='ck_test_scores_date_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_scores_profile_id', 'test_scores', ['profile_id'], unique=False)
    op.create_index('ix_test_scores_profile_test_type', 'test_scores', ['profile_id', 'test_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_scores_profile_test_type', table_name='test_scores')
    op.drop_index('ix_test_scores_profile_id', table_name='test_scores')
    op.drop_table('test_scores')
    op.drop_index('uq_education_primary_per_profile', table_name='education', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_education_profile_id', table_name='education')
    op.drop_table('education')
    op.drop_index('ix_profiles_degree_level', table_name='profiles')
    op.drop_index('ix_profiles_country_of_residence', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
