"""add users and profile ownership

Revision ID: ba09eb02910b
Revises: 03d2e7c43211
Create Date: 2026-09-27 10:20:13.044682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba09eb02910b'
down_revision: Union[str, Sequence[str], None] = '03d2e7c43211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('profiles', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint('uq_profiles_user_id', 'profiles', ['user_id'])
    op.create_foreign_key(
        'profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_user_id_fkey', 'profiles', type_='foreignkey')
    op.drop_constraint('uq_profiles_user_id', 'profiles', type_='unique')
    op.drop_column('profiles', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
