"""create opportunities, sources and requirements tables

Revision ID: f32f798afa83
Revises: 
Create Date: 2026-09-24 23:29:09.997965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f32f798afa83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('opportunity_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host_name', sa.String(length=255), nullable=True),
    sa.Column('official_url', sa.String(length=2000), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_type', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=True),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('location_mode', sa.String(length=16), nullable=False),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("deadline_type IN ('fixed', 'rolling', 'none')", name='ck_opportunities_deadline_type'),
    sa.CheckConstraint("location_mode IN ('onsite', 'hybrid', 'remote', 'unknown')", name='ck_opportunities_location_mode'),
    sa.CheckConstraint("opportunity_type IN ('scholarship', 'internship', 'fellowship', 'research_program', 'summer_school', 'hackathon', 'competition', 'open_source_program', 'grant', 'conference', 'course', 'job', 'other')", name='ck_opportunities_opportunity_type'),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed', 'archived')", name='ck_opportunities_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_opportunities_status_deadline', 'opportunities', ['status', 'deadline_at'], unique=False)
    op.create_index('ix_opportunities_type_status', 'opportunities', ['opportunity_type', 'status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("source_type IN ('official_page', 'partner_api', 'manual_entry', 'scraped', 'mirror')", name='ck_sources_source_type'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_opportunity_id', 'sources', ['opportunity_id'], unique=False)
    op.create_index('uq_sources_primary_per_opportunity', 'sources', ['opportunity_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('category', sa.String(length=32), server_default='other', nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('academic', 'language', 'demographic', 'document', 'logistics', 'timing', 'other')", name='ck_requirements_category'),
    sa.CheckConstraint("kind IN ('numeric_threshold', 'set_membership', 'equality', 'boolean_flag', 'date_gate', 'skill_set', 'any_of', 'unparsed')", name='ck_requirements_kind'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_opportunity_order', 'requirements', ['opportunity_id', 'order_index'], unique=False)
    op.create_index('ix_requirements_source_id', 'requirements', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requirements_source_id', table_name='requirements')
    op.drop_index('ix_requirements_opportunity_order', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('uq_sources_primary_per_opportunity', table_name='sources', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_sources_opportunity_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_opportunities_type_status', table_name='opportunities')
    op.drop_index('ix_opportunities_status_deadline', table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
